import type { Language } from './chapters';

export const SLUG_TO_ID_CPP: Record<string, string> = {
  'cpp-intro': '01-intro',
  'cpp-environment-setup': '02-setup',
  'cpp-basic-syntax': '03-basic-syntax',
  'cpp-comments': '04-comments',
  'cpp-data-types': '05-data-types',
  'cpp-variable-types': '06-variable-types',
  'cpp-variable-scope': '07-variable-scope',
  'cpp-constants-literals': '08-constants-literals',
  'cpp-modifier-types': '09-modifier-types',
  'cpp-storage-classes': '10-storage-classes',
  'cpp-operators': '11-operators',
  'cpp-loops': '12-loops',
  'cpp-decision': '13-decision',
  'cpp-functions': '14-functions',
  'cpp-numbers': '15-numbers',
  'cpp-arrays': '16-arrays',
  'cpp-strings': '17-strings',
  'cpp-pointers': '18-pointers',
  'cpp-references': '19-references',
  'cpp-date-time': '20-date-time',
  'cpp-basic-input-output': '21-io',
  'cpp-struct': '22-struct',
  'cpp-vector': '23-vector',
  'cpp-data-structures': '24-data-structures',
  'cpp-classes-objects': '25-classes-objects',
  'cpp-inheritance': '26-inheritance',
  'cpp-overloading': '27-overloading',
  'cpp-polymorphism': '28-polymorphism',
  'cpp-data-abstraction': '29-data-abstraction',
  'cpp-data-encapsulation': '30-data-encapsulation',
  'cpp-interfaces': '31-interfaces',
  'cpp-files-streams': '32-files-streams',
  'cpp-exceptions-handling': '33-exceptions',
  'cpp-dynamic-memory': '34-dynamic-memory',
  'cpp-namespaces': '35-namespaces',
  'cpp-templates': '36-templates',
  'cpp-preprocessor': '37-preprocessor',
  'cpp-signal-handling': '38-signal-handling',
  'cpp-multithreading': '39-multithreading',
  'cpp-web-programming': '40-web-programming',
};

export const SLUG_TO_ID_PYTHON: Record<string, string> = {
  'python-intro': '01-intro',
  'python-install': '02-install',
  'python-chinese-encoding': '03-encoding',
  'python2-vscode-setup': '04-vscode',
  'python-basic-syntax': '05-basic-syntax',
  'python-variable-types': '06-variable-types',
  'python-operators': '07-operators',
  'python-if-statement': '08-if-statement',
  'python-loops': '09-loops',
  'python-while-loop': '10-while-loop',
  'python-for-loop': '11-for-loop',
  'python-nested-loops': '12-nested-loops',
  'python-break-statement': '13-break-statement',
  'python-continue-statement': '14-continue-statement',
  'python-pass-statement': '15-pass-statement',
  'python-numbers': '16-numbers',
  'python-strings': '17-strings',
  'python-lists': '18-lists',
  'python-tuples': '19-tuples',
  'python-dictionary': '20-dictionary',
  'python-date-time': '21-date-time',
  'python-functions': '22-functions',
  'python-modules': '23-modules',
  'python-files-io': '24-files-io',
  'file-methods': '25-file-methods',
  'python-exceptions': '26-exceptions',
  'os-file-methods': '27-os-file-methods',
  'python-built-in-functions': '28-built-in-functions',
  'python-object': '29-object',
  'python-reg-expressions': '30-reg-expressions',
  'python-cgi': '31-cgi',
  'python-mysql': '32-mysql',
  'python-socket': '33-socket',
  'python-email': '34-email',
  'python-multithreading': '35-multithreading',
  'python-xml': '36-xml',
  'python-gui-tkinter': '37-gui-tkinter',
  'python-2x-3x': '38-2x-3x',
  'python-ide': '39-ide',
  'python-json': '40-json',
  'python-ai-draw': '41-ai-draw',
  'python-100-examples': '42-100-examples',
  'python-quiz': '43-quiz',
};

export const SLUG_TO_ID_JAVA: Record<string, string> = {
  'java-intro': '01-intro',
  'java-environment-setup': '02-env-setup',
  'java-basic-syntax': '03-basic-syntax',
  'java-comments': '04-comments',
  'java-object-classes': '05-object-classes',
  'java-basic-datatypes': '06-basic-datatypes',
  'java-variable-types': '07-variable-types',
  'java-variable-naming-rules': '08-naming-rules',
  'java-modifier-types': '09-modifier-types',
  'java-operators': '10-operators',
  'java-loop': '11-loop',
  'java-if-else-switch': '12-if-else-switch',
  'java-switch-case': '13-switch-case',
  'java-number': '14-number',
  'java-character': '15-character',
  'java-string': '16-string',
  'java-stringbuffer': '17-stringbuffer',
  'java-array': '18-array',
  'java-date-time': '19-date-time',
  'java-regular-expressions': '20-regex',
  'java-methods': '21-methods',
  'java-constructor': '22-constructor',
  'java-files-io': '23-files-io',
  'java-scanner-class': '24-scanner',
  'java-exceptions': '25-exceptions',
  'java-inheritance': '26-inheritance',
  'java-override-overload': '27-override-overload',
  'java-polymorphism': '28-polymorphism',
  'java-abstraction': '29-abstraction',
  'java-encapsulation': '30-encapsulation',
  'java-interfaces': '31-interfaces',
  'java-enum': '32-enum',
  'java-package': '33-package',
  'java-reflection': '34-reflection',
  'java-data-structures': '35-data-structures',
  'java-collections': '36-collections',
  'java-arraylist': '37-arraylist',
  'java-linkedlist': '38-linkedlist',
  'java-hashset': '39-hashset',
  'java-hashmap': '40-hashmap',
  'java-iterator': '41-iterator',
  'java-object-class': '42-object-class',
  'java-nio-file': '43-nio-file',
  'java-generics': '44-generics',
  'java-serialization': '45-serialization',
  'java-networking': '46-networking',
  'java-sending-email': '47-email',
  'java-multithreading': '48-multithreading',
  'java-applet-basics': '49-applet',
  'java-documentation': '50-documentation',
  'java-examples': '51-examples',
  'java8-new-features': '52-java8',
  'java-mysql-connect': '53-mysql',
  'java9-new-features': '54-java9',
  'java-quiz': '55-quiz',
  'java-libs': '56-libs',
};

export const SLUG_TO_ID_MAP: Record<Language, Record<string, string>> = {
  cpp: SLUG_TO_ID_CPP,
  python: SLUG_TO_ID_PYTHON,
  java: SLUG_TO_ID_JAVA,
};

export function getIdFromUrl(url: string, language: Language): string {
  const slug = url.split('/').pop()?.replace('.html', '') || '';
  if (language === 'python') return SLUG_TO_ID_PYTHON[slug] || slug;
  if (language === 'java') return SLUG_TO_ID_JAVA[slug] || slug;
  return SLUG_TO_ID_CPP[slug] || slug;
}
